doctrine:
    dbal:
        #url: mysql://dbu2709052:Boxracing29@db5007501938.hosting-data.io:3306/dbs6181235
        #mysql://boxracinnnbox:Boxracing29@boxracinnnbox.mysql.db:3306/boxracinnnbox
        #mysql://boxracinnnbox:Boxracing29@boxracinnnbox.mysql.db:3306/boxracinnnbox
        url: mysql://root:@127.0.0.1:3306/boxracinnnbox?serverVersion=mariadb-10.4.11
        #'%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
