swiftmailer:
    transport: sendmail
    username: contact@box-racing.fr
    password: ''
    auth_mode: login
    disable_delivery: false
    encryption: ssl
    port: 465
    host: ssl0.ovh.net
    #spool: 
      #type: file
      #path: '%kernel.project_dir%/var/spool'
